### ISSUE TITLE
Does the CKKSVector class automatically encode data, and it possible to encode N-dimensional tensors for N>1?

### ISSUE THREAD

**Issue by ray-dedhia** [OpenMined/TenSEAL#211]
## Question
**Does the CKKSVector class automatically encode data, and it possible to encode N-dimensional tensors for N>1?**

## Further Information
1. Does the CKKSVector class automatically encode values before encrypting them? (It seems like this might the case from https://github.com/OpenMined/TenSEAL/pull/7, but I'm not 100% sure.) What about the CKKSTensor?

2. The `test_ckks_encoder` function in test_encode_decode.py shows how to encode, encrypt, and decrypt 1D tensor data, but is there a way to encode N-dimensional data for N>1 (since `_sealapi_cpp.CKKSEncoder` appears to only accept scalar and 1D tensor data)?

**Comment by youben11** [comment]
Hi @ray-dedhia 
1. Yeah, CKKSVector and the other tensors encode data automatically before encryption.
2. If you want to use N-dimentional tensor, you would prefer to use CKKSTensor instead of CKKSVector. The latter is more optimized for specific use case that can be represented using a vector, but is not flexible enough for higher value of N as the CKKSTensor.

**Comment by ray-dedhia** [comment]
Thanks!

**Comment by ray-dedhia** [comment]
By optimizations, do you mean that CKKSVector uses vector encoding, i.e. encodes the entire input 1D array of data into a single plaintext before encrypting it into a single ciphertext? 

And CKKSTensor encodes the data points in the input N-dimensional array one-by-one into multiple plaintext before encrypting them into multiple ciphertext (which is why it takes much longer to perform encryption)? Or am I misunderstanding?

**Comment by youben11** [comment]
You are right. However, CKKSTensor also provides a way to batch multiple matrices (e.g. 4096) into a matrix of ciphertext. So we can still use the packing capability of ciphertext in CKKSTensor, but serving a different purpose. In CKKSVector, the packing is considered as a useful dimension, an we can perform dot product across that dimension. However, in CKKSTensor, packing can only be used to batch multiple values of the same shape in order to perform parallel computation, but the batch axis is never considered during computation. 5 batched matrices will look similar to 1 matrix or 100 other batched matrices, they all have a shape of NxM but with a different number of batched elements.

**Comment by ray-dedhia** [comment]
Thanks!
