### ISSUE TITLE
How do I set `poly_modulus_degree` to values higher than 2^15 (32768)?

### ISSUE THREAD

**Issue by ray-dedhia** [OpenMined/TenSEAL#215]
## Question
**Is there a way to set `poly_modulus_degree` to values higher than 2^15 (32768)?**

## Further Information
When I tried to set `poly_modulus_degree` to 2^16 (65536) while creating a context object, I got a ValueError message telling me the parameters I had chosen were invalid.   

## Additional Context
I don't think this is an issue with what values Microsoft SEAL accepts as valid for the `poly_modulus_degree`, because the version of TenSEAL that I'm using (v0.3.0a1) is using a version of Microsoft SEAL ([SEAL @ 3eea435](https://github.com/OpenMined/TenSEAL/tree/v0.3.0a1/third_party)) that supports values of poly_modulus_degree up to 2^17 (131072) (as stated in the [defines.h](https://github.com/microsoft/SEAL/blob/main/native/src/seal/util/defines.h#L52) file).

**Comment by bcebere** [comment]
Hello @ray-dedhia 

There are 2 discussions here:
1. You are using the default values for "coeff_mod_bit_sizes" parameter.
 - In this scenario, for both BFV and CKKS, we generate coeff modulus using BFVDefault([code](https://github.com/OpenMined/TenSEAL/blob/master/tenseal/cpp/context/sealcontext.cpp#L21))
 - We use the default sec_level there, which is for 128 bits. ([code](https://github.com/microsoft/SEAL/blob/main/native/src/seal/modulus.h#L476) )
  - SEAL check the parameters for MaxBitCount ([code](https://github.com/microsoft/SEAL/blob/main/native/src/seal/modulus.cpp#L118) ).
   - But as you can see [here](https://github.com/microsoft/SEAL/blob/main/native/src/seal/util/hestdparms.h), poly_mod 65536 is not supported by default, unless you set the security level to none. But that is not supported by BFVDefault.
   - You can also see [here](https://github.com/microsoft/SEAL/blob/main/native/src/seal/util/globals.cpp#L62-L70) that the largest supported polynomial modulus is 32768.
   - So you have to explicitly specify coeff_mod_bit_sizes.
   
2. You specify coeff_mod_bit_sizes in your params. Here you might get in another issue since the individual coefficient modulus cannot exceed 64 bits.

Looking through SEAL checks, it doesn't seem officially supported. To cite from their issue tracker:
> So in theory, using a CoeffModulus which permits depth 60 evaluations is not disallowed by SEAL. 
poly_modulus_degree = 65536 should be about right for depth 60. It is not provided in the default parameters since HE standardization security whitepaper has not yet standardized security parameters for 65536 and above. 


If you can detail your use case, maybe there is another workaround here.

**Comment by ray-dedhia** [comment]
Hi, thanks for replying so quickly! I'm trying to encode vectors of sizes > 16384. The simplest workaround would probably be encoding the data in chunks. 

However, I was wondering, is there a way to create the context object with a value of coefficient modulus that will allow for values of `poly_modulus_degree` that are higher than 32768, maybe by overriding the context class constructor?

**Comment by bcebere** [comment]
Actually, for the vector length, there is a PR pending here https://github.com/OpenMined/TenSEAL/pull/213
After that's merged, you can use the same API for arbitrarily sized vectors.

As I said, SEAL nor the HE standard support poly_modulus_degree > 32768 officially. We don't actually block anything in our constructor, but if you provide a compatible coeff_mod_bit_sizes with poly_mod 65536, it should work. But the ciphertexts will get pretty huge for those values.

**Comment by ray-dedhia** [comment]
Thanks! Could you advise me on how to find a compatible `coeff_bit_mod_sizes` value for a `poly_modulus_degree` of 65536? I looked it up, but don't have the mathematical background to understand everything.

**Comment by bcebere** [comment]
I looked through the SEAL code again, and for the creation of encryption parameters, they explicitly
 state:

> In Microsoft SEAL the degree of the polynomial modulus must be   a power of 2 (e.g.  1024, 2048, 4096, 8192, 16384, or 32768).

It is not supported by them or by the standard, so I cannot recommend good values.

For security reasons, using poly_mod 8192 is just fine.
If you want to encrypt a larger vector, please wait for the merge of the PR mentioned above.

Thanks!

**Comment by ray-dedhia** [comment]
Okay, thanks again for all the help!
