### ISSUE TITLE
Using dot() or matmul() functions for CKKSTensor

### ISSUE THREAD

**Issue by ymsaputra** [OpenMined/TenSEAL#377]
I tried to use dot and matmul functions when I use CKKSTensor for the 2D weight matrix. However, it seems that both functions do not work when CKKSTensor is applied. Both functions work for CKKSVector.

I tried to implement Deep Learning approach in TenSEAL for encrypted training. Here, I have tried using torch.matmul but it raises an error regarding the use of matmul functions as follows:

Traceback (most recent call last):
  File "new3b3.py", line 570, in <module>
    enc_client_update(enc_client_models[i], ctx_training, enc_x_train[enc_client_idx[i]], enc_y_train[enc_client_idx[i]], epoch=epochs) 
  File "new3b3.py", line 448, in enc_client_update
    enc_out1, enc_out2, enc_out3, enc_out4 = client_model.forward(enc_x)
  File "new3b3.py", line 289, in forward
    enc_out1 = torch.matmul(enc_x, self.weight1) + self.bias1
TypeError: matmul(): argument 'input' (position 1) must be Tensor, not CKKSTensor

Is there any way to make both functions work in TenSEAL?

**Comment by Ti-Oluwanimi** [comment]
Were you able to encrypt using CKKS tensor

**Comment by ymsaputra** [comment]
Yeah but not for matrix multiplication, because there is no matmul function, and dot() also does not work

**Comment by bcebere** [comment]
Hello,

As you can see here, CKKSTensor provides the implementations for dot and matmul https://github.com/OpenMined/TenSEAL/blob/main/tenseal/tensors/ckkstensor.py#L106

Your error 
```
TypeError: matmul(): argument 'input' (position 1) must be Tensor, not CKKSTensor
```

appears because you try to pass to torch a CKKSTensor, and it is not compatible.

The main reason is because we cannot provide a backprop implementation, so you have to handle only the CKKSTensor class.
