### ISSUE TITLE
A aggregation function for an encrypted vector (add_many/multiply_many)

### ISSUE THREAD

**Issue by Christopher-Wang** [OpenMined/TenSEAL#74]
## Feature Description
A single encrypted TenSEAL vector should be able to be naively aggregated by either a sum or product. 

## Is your feature request related to a problem?
This would be especially useful for common operations such as dot product and euclidean distance. 

## What alternatives have you considered?
Currently the only known method I understand might for summation work is to perform a matrix multiplication with an identity vector which is not ideal.

## Additional Context
Ideally the operation would look something like 
`encrypted_vec.add_many()`

**Comment by youben11** [comment]
Hi @Christopher-Wang and thanks for your input! 

I just want to clarify your feature request, so by `encrypted_vec.add_many()` do you mean summing up the slots of the vector? like if you have a vector encrypting the vector `[1, 2, 3]`, this method will result in a vector encrypted a single value (`[6]`), is that right?

**Comment by Christopher-Wang** [comment]
Yes. Similar to the Evaluator::multiply_many and Evaluator::add_many definitions in the SEAK 2.0 documentation. I also check and currently there is no way to encrypt a matrix therefore the matmul workaround is impossible.

**Comment by youben11** [comment]
`Evaluator::multiply_many` and `Evaluator::add_many` actually do the operations on *many* ciphertexts in an element-wise fashion, and not on the slots of the same ciphertext.

If what you meant is the feature I described in my last comment, it shouldn't be a big deal to implement, it just wasn't a priority, but since there is a need for that, I can take a look at it and ping you when a PR is ready, you can also help us with reviews to let us know if the API for doing those operations looks good. Does this work for you?

**Comment by Christopher-Wang** [comment]
Perfect thanks! I appreciate it
