### ISSUE TITLE
CKKS multiplication crashes with "scale out of bounds"

### ISSUE THREAD

**Issue by bcebere** [OpenMined/TenSEAL#78]
## Description
Testcase fails with 
```unknown file: Failure
C++ exception with description "scale out of bounds" thrown in the test body.
[  FAILED  ] CKKSVectorTest.TestCKKSMulMany (79 ms)
```

## How to Reproduce
https://github.com/OpenMined/TenSEAL/blob/gtest/tests/cpp/tensors/ckksvector_test.cpp#L98

**Comment by dhuynh95** [comment]
I think you did too many multiplications. You set {60, 40, 40, 60} for the primes used in the moduli, therefore you can do only 2 multiplications while you asked to do 5.

**Comment by apignet** [comment]
Hi.
This issue is closed, but I have the same problems. How did you solved it ? 

I am trying to evaluate a polynomial expression of a dot product. 

 The SEAL documentation explains that I missed a relinearization or a rescale step, but I thought both operations are done automatically using tenseal ? 

context = ts.context(ts.SCHEME_TYPE.CKKS, 8192, coeff_mod_bit_sizes=[60, 40, 40, 60])
context.global_scale = pow(2,40)
context.generate_galois_keys()

plain_vector = [-1, 0,9, 6, 90 ]
vec = np.array(plain_vector)
plain_vector2 = [-1 ,3 , 2,3,0 ]
vec2= np.array(plain_vector2)

encrypted_vector = ts.ckks_vector(context, plain_vector)
encrypted_vector2 = ts.ckks_vector(context, plain_vector2)

Edot = encrypted_vector.dot(encrypted_vector)
Udot= vec.dot(vec2)

(Edot*Edot) * (Edot*[0.5])

>> ValueError: scale out of bounds

**Comment by bcebere** [comment]
Sorry, my bad, my understanding was that I was testing it wrong. I'll leave it open.

**Comment by youben11** [comment]
Hi @apignet, you are trying to perform 3 multiplications in a chain when your parameters are set to support two multiplications only. You will need to increase the parameters while creating the context in `context = ts.context(ts.SCHEME_TYPE.CKKS, 8192, coeff_mod_bit_sizes=[60, 40, 40, 60])` in order to support 3 multiplications.

**Comment by apignet** [comment]
Reading SEAL example and this issue `[64](ehttps://github.com/microsoft/SEAL/issues/64 )`, I understood that the relinearization/rescaling operations transform a cipertext of level l in a ciphertext of level l-1. Therefore, with auto-relin and auto-rescale, I did not understand why I am not able to support more than 2 multiplications.

**Comment by youben11** [comment]
The auto_|relin|rescale] features of TenSEAL allow users to focus on the computation without the need to do the relinearization/rescaling, but those operations are still done by TenSEAL. A new ciphertext has some coefficient modulus q and every time a multiplication is done and we perform a rescaling, the modulus goes down, until it reaches some value that can no longer holds the coefficient with a certain scale, so for being able to perform many multiplication for a certain scale, you will need to choose your parameters accordingly.

**Comment by apignet** [comment]
okay thank you @youben11 
I am going to look further on this choice of parameters
